---
stages:
- name: Build
  inputs:
  - type: git
    branch: master
    service: ${SAMPLE_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: grunt
    script: |-
      export PATH=/opt/IBM/node-v4.2/bin:$PATH
      npm install
      npm install -g bower
      bower install
      npm install -g grunt-cli
      grunt build
      tar -czf node_modules.tar.gz node_modules
      rm -rf node_modules
- name: Run Unit Test
  inputs:
  - type: job
    stage: Build
    job: Build
  triggers:
  - type: stage
  jobs:
  - name: Linting and Unit Tests
    type: tester
    script: |-
      tar -xzf node_modules.tar.gz
      grunt test:dist
    enable_tests: true
    test_file_pattern: test/reports/unit-tests.xml
- name: Active Deploy
  inputs:
  - type: job
    stage: Build
    job: Build
  triggers:
  - type: stage
  properties:
  - name: NAME
    value: ''
    type: text
  - name: GROUP_SIZE
    value: '1'
    type: text
  - name: TEST_RESULT_FOR_AD
    value: ''
    type: text
  - name: APP_NAME
    value: ${CF_APP}
    type: text
  - name: SAUCE_USERNAME
    value: ${SAUCE_USER}
    type: text
  - name: SAUCE_ACCESS_KEY
    value: ${SAUCE_KEY}
    type: text
  jobs:
  - name: Deploy Single Instance
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash
      NAME="${CF_APP}_${BUILD_NUMBER}"
      cf push "${NAME}" --no-route -i 1 -m 64M
      export NAME
  - name: Begin Active Deploy
    type: deployer
    extension_id: ibm.devops.services.pipeline.devops.ad_start
    target:
      url: ${CF_TARGET_URL}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
    RAMPDOWN_DURATION: 1m
    RAMPUP_DURATION: 1m
    COMMAND: |-
      #!/bin/bash
      source ${EXT_DIR}/git_util.sh
      git_retry clone https://github.com/Osthanes/update_service.git activedeploy
      activedeploy/activedeploy_step_1.sh
  - name: e2e tests
    type: tester
    fail_stage: false
    enable_tests: true
    test_file_pattern: test/reports/e2e-tests.xml
    extension_id: ibm.devops.services.pipeline.saucelabs
    target:
      url: ${CF_TARGET_URL}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
    ACCESS: ${SAUCE_KEY}
    DL_ASSETS: 'true'
    SELECT_CMD: custom
    USER_ID: ${SAUCE_USER}
    COMMAND: |-
      #!/bin/bash
      tar -xzf node_modules.tar.gz
      set -x
      export PATH=/opt/IBM/node-v4.2/bin:$PATH

      # Start by checking if a previous test failed. If so, quit now.
      # Make sure exit code is 0 (success).
      if [[ -n ${TEST_RESULT_FOR_AD} ]] && (( ${TEST_RESULT_FOR_AD} )); then
        exit 0
      fi
      # invoke tests here

      # Set TEST_RESULT_FOR_AD: 0 for successful tests, non-zero for failures
      # 'exit' SHOULD NOT be used in this script after this point.
      export TEST_RESULT_FOR_AD=1
      if (grunt e2e); then
        export TEST_RESULT_FOR_AD=0
      fi
  - name: Complete Active Deploy
    type: deployer
    extension_id: ibm.devops.services.pipeline.devops.ad_finish
    target:
      url: ${CF_TARGET_URL}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
    COMMAND: |-
      #!/bin/bash
      if [[ -z ${TEST_RESULT_FOR_AD} ]]; then
        TEST_RESULT_FOR_AD=1;
      fi
      echo resultater
      echo ${TEST_RESULT_FOR_AD}
      source ${EXT_DIR}/git_util.sh
      git_retry clone https://github.com/Osthanes/update_service.git activedeploy
      activedeploy/activedeploy_step_2.sh
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
